
def is_palindrome(text: str) -> bool:
    ...

def fibonacci(n: int) -> int:
    ...

def count_vowels(text: str) -> int:
    ...

def calculate_discount(price: float, discount: float) -> float:
    ...

def flatten_list(nested_list: list) -> list:
    ...

def word_frequencies(text: str) -> dict:
    ...

def is_prime(n: int) -> bool:
    ...